import React, { useState } from 'react';
import { supabase } from '../supabaseClient';

interface OnboardingWizardProps {
  onComplete: () => void;
}

export const OnboardingWizard: React.FC<OnboardingWizardProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);

  // Form states
  const [board, setBoard] = useState('');
  const [customBoard, setCustomBoard] = useState('');
  const [studentClass, setStudentClass] = useState('');
  const [examName, setExamName] = useState('');
  const [examDate, setExamDate] = useState('');
  const [studyHours, setStudyHours] = useState('4');
  
  // Syllabus & Subjects generated by AI
  const [subjects, setSubjects] = useState<string[]>([]);
  const [syllabus, setSyllabus] = useState<{ subject: string; chapters: string[] }[]>([]);
  const [editingChapter, setEditingChapter] = useState<{ subIndex: number; chapIndex: number; text: string } | null>(null);

  // Slots
  const [slots, setSlots] = useState<{ slotNumber: number; title: string; duration: string }[]>([
    { slotNumber: 1, title: 'Morning Slot', duration: '2 hours' },
    { slotNumber: 2, title: 'Evening Slot', duration: '2 hours' }
  ]);

  // Simulate AI generating perfect syllabus based on board & exam
  const generateAISyllabus = () => {
    setLoading(true);
    setTimeout(() => {
      // Mocking AI generated board-recommended syllabus structure
      const mockSyllabus = [
        {
          subject: 'Physics',
          chapters: ['Electric Charges and Fields', 'Electrostatic Potential', 'Current Electricity', 'Moving Charges and Magnetism']
        },
        {
          subject: 'Chemistry',
          chapters: ['Solutions', 'Electrochemistry', 'Chemical Kinetics', 'Coordination Compounds']
        },
        {
          subject: 'Mathematics',
          chapters: ['Relations and Functions', 'Matrices', 'Determinants', 'Continuity and Differentiability']
        }
      ];
      setSyllabus(mockSyllabus);
      setLoading(false);
      setStep(5); // Move to syllabus review step
    }, 1500);
  };

  const handleFinish = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        // Save onboarding data to Supabase profile or user metadata
        await supabase.auth.updateUser({
          data: {
            onboarding_completed: true,
            board: board === 'Other' ? customBoard : board,
            class: studentClass,
            exam_name: examName,
            exam_date: examDate,
            study_hours: studyHours,
            syllabus: syllabus,
            slots: slots
          }
        });
      }
      onComplete();
    } catch (err: any) {
      console.error(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-md flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 w-full max-w-xl shadow-2xl text-white my-8">
        
        {/* Progress Bar */}
        <div className="w-full bg-slate-800 h-2 rounded-full mb-6 overflow-hidden">
          <div 
            className="bg-indigo-600 h-full transition-all duration-300"
            style={{ width: `${(step / 6) * 100}%` }}
          ></div>
        </div>

        {/* STEP 1: Board Selection */}
        {step === 1 && (
          <div>
            <h2 className="text-2xl font-bold mb-2">Select Your Education Board</h2>
            <p className="text-slate-400 text-sm mb-6">Choose your board so we can tailor the exact syllabus for you.</p>
            
            <div className="grid grid-cols-2 gap-3 mb-6">
              {['CBSE', 'ICSE', 'UP Board', 'Bihar Board', 'State Board', 'Other'].map((b) => (
                <button
                  key={b}
                  type="button"
                  onClick={() => setBoard(b)}
                  className={`p-3 rounded-xl border text-left font-medium text-sm transition-all ${
                    board === b ? 'border-indigo-500 bg-indigo-600/20 text-white' : 'border-slate-800 bg-slate-800/50 text-slate-300 hover:border-slate-700'
                  }`}
                >
                  {b}
                </button>
              ))}
            </div>

            {board === 'Other' && (
              <input
                type="text"
                placeholder="Enter your board name"
                value={customBoard}
                onChange={(e) => setCustomBoard(e.target.value)}
                className="w-full bg-slate-800 border border-slate-700 rounded-lg px-4 py-2.5 text-white mb-6 text-sm"
              />
            )}

            <button
              disabled={!board || (board === 'Other' && !customBoard)}
              onClick={() => setStep(2)}
              className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-medium py-2.5 rounded-lg transition"
            >
              Next Step
            </button>
          </div>
        )}

        {/* STEP 2: Class & Exam Details */}
        {step === 2 && (
          <div>
            <h2 className="text-2xl font-bold mb-2">Academic Details</h2>
            <p className="text-slate-400 text-sm mb-6">Which class are you studying in and what is your target?</p>

            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">Current Class / Grade</label>
                <select
                  value={studentClass}
                  onChange={(e) => setStudentClass(e.target.value)}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-4 py-2.5 text-white text-sm"
                >
                  <option value="">Select Class</option>
                  <option value="Class 10">Class 10</option>
                  <option value="Class 11">Class 11</option>
                  <option value="Class 12">Class 12</option>
                  <option value="Dropper / College">Dropper / College</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">Target Examination</label>
                <input
                  type="text"
                  placeholder="e.g., Board Exams, NEET, JEE Main"
                  value={examName}
                  onChange={(e) => setExamName(e.target.value)}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-4 py-2.5 text-white text-sm"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-300 mb-1">Examination Date</label>
                <input
                  type="date"
                  value={examDate}
                  onChange={(e) => setExamDate(e.target.value)}
                  className="w-full bg-slate-800 border border-slate-700 rounded-lg px-4 py-2.5 text-white text-sm"
                />
              </div>
            </div>

            <div className="flex gap-3">
              <button onClick={() => setStep(1)} className="w-1/3 bg-slate-800 hover:bg-slate-700 text-slate-300 py-2.5 rounded-lg text-sm">Back</button>
              <button 
                disabled={!studentClass || !examName} 
                onClick={() => setStep(3)} 
                className="w-2/3 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white py-2.5 rounded-lg text-sm"
              >
                Next Step
              </button>
            </div>
          </div>
        )}

        {/* STEP 3: Study Hours & Goal */}
        {step === 3 && (
          <div>
            <h2 className="text-2xl font-bold mb-2">Daily Study Commitment</h2>
            <p className="text-slate-400 text-sm mb-6">How many hours do you plan to study daily?</p>

            <div className="mb-6">
              <div className="text-3xl font-bold text-indigo-400 text-center mb-4">{studyHours} Hours / Day</div>
              <input
                type="range"
                min="1"
                max="14"
                value={studyHours}
                onChange={(e) => setStudyHours(e.target.value)}
                className="w-full accent-indigo-500 cursor-pointer"
              />
            </div>

            <div className="flex gap-3">
              <button onClick={() => setStep(2)} className="w-1/3 bg-slate-800 hover:bg-slate-700 text-slate-300 py-2.5 rounded-lg text-sm">Back</button>
              <button 
                onClick={() => {
                  generateAISyllabus();
                }} 
                className="w-2/3 bg-indigo-600 hover:bg-indigo-500 text-white py-2.5 rounded-lg text-sm flex items-center justify-center gap-2"
              >
                {loading ? 'AI is generating syllabus...' : '✨ Generate AI Syllabus'}
              </button>
            </div>
          </div>
        )}

        {/* STEP 4: AI Loading State */}
        {step === 4 && loading && (
          <div className="text-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-500 mx-auto mb-4"></div>
            <h3 className="text-lg font-medium text-white">Analyzing {board} Syllabus...</h3>
            <p className="text-slate-400 text-sm mt-1">Our AI is fetching official recommended chapters for your exam.</p>
          </div>
        )}

        {/* STEP 5: Review & Edit AI Syllabus */}
        {step === 5 && (
          <div>
            <h2 className="text-2xl font-bold mb-2">Review Recommended Syllabus</h2>
            <p className="text-slate-400 text-sm mb-4">AI generated this syllabus as per your board. You can edit chapters if needed.</p>

            <div className="space-y-4 max-h-64 overflow-y-auto pr-2 mb-6">
              {syllabus.map((s, sIdx) => (
                <div key={s.subject} className="bg-slate-800/60 p-3 rounded-xl border border-slate-700/50">
                  <h4 className="font-semibold text-indigo-400 mb-2">{s.subject}</h4>
                  <ul className="space-y-2">
                    {s.chapters.map((chap, cIdx) => (
                      <li key={cIdx} className="flex items-center justify-between text-sm bg-slate-900/60 px-3 py-1.5 rounded-lg">
                        <span>{chap}</span>
                        <button
                          onClick={() => {
                            const newName = prompt('Edit chapter name:', chap);
                            if (newName) {
                              const updated = [...syllabus];
                              updated[sIdx].chapters[cIdx] = newName;
                              setSyllabus(updated);
                            }
                          }}
                          className="text-xs text-indigo-400 hover:underline"
                        >
                          Edit
                        </button>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>

            <button 
              onClick={() => setStep(6)} 
              className="w-full bg-indigo-600 hover:bg-indigo-500 text-white py-2.5 rounded-lg text-sm font-medium"
            >
              Confirm & Setup Slots
            </button>
          </div>
        )}

        {/* STEP 6: Initial Simple Time Slots */}
        {step === 6 && (
          <div>
            <h2 className="text-2xl font-bold mb-2">Initial Time Slots</h2>
            <p className="text-slate-400 text-sm mb-4">Keep it simple for now. You can customize a full detailed timetable later from the dashboard.</p>

            <div className="space-y-3 mb-6">
              {slots.map((slot, index) => (
                <div key={index} className="bg-slate-800 p-3 rounded-xl flex items-center justify-between border border-slate-700">
                  <div>
                    <div className="font-semibold text-sm">Slot {slot.slotNumber}: {slot.title}</div>
                    <div className="text-xs text-slate-400">Duration: {slot.duration}</div>
                  </div>
                  <button
                    onClick={() => {
                      const newTitle = prompt('Edit slot name:', slot.title);
                      if (newTitle) {
                        const updated = [...slots];
                        updated[index].title = newTitle;
                        setSlots(updated);
                      }
                    }}
                    className="text-xs text-indigo-400 hover:underline"
                  >
                    Edit
                  </button>
                </div>
              ))}

              <button
                onClick={() => {
                  setSlots([...slots, { slotNumber: slots.length + 1, title: `Slot ${slots.length + 1}`, duration: '2 hours' }]);
                }}
                className="w-full border border-dashed border-slate-700 hover:border-indigo-500 text-slate-400 hover:text-indigo-400 py-2 rounded-xl text-sm transition"
              >
                + Add Another Slot
              </button>
            </div>

            <button
              disabled={loading}
              onClick={handleFinish}
              className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-medium py-2.5 rounded-lg text-sm transition"
            >
              {loading ? 'Finalizing Setup...' : '🚀 Launch My Dashboard'}
            </button>
          </div>
        )}

      </div>
    </div>
  );
};